"use client";

import { useQuery } from "@tanstack/react-query";
import { contractsApi } from "@/lib/api";
import { useParams } from "next/navigation";
import Link from "next/link";
import { format } from "date-fns";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Download, Loader2 } from "lucide-react";
import { STATUS_COLORS, STATUS_LABELS } from "@/lib/types";

export default function ContractDetailPage() {
  const { id } = useParams<{ id: string }>();

  const { data, isLoading } = useQuery({
    queryKey: ["contract", id],
    queryFn: () => contractsApi.get(id),
  });

  const contract = data?.data;

  if (isLoading) {
    return (
      <div className="flex h-[50vh] items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (!contract) {
    return <div className="py-20 text-center"><p>Contract not found</p></div>;
  }

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link href="/dashboard/contracts">
            <Button variant="ghost" size="icon"><ArrowLeft className="h-5 w-5" /></Button>
          </Link>
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-2xl font-bold capitalize">{contract.contract_type.replace(/_/g, " ")}</h1>
              <Badge className={STATUS_COLORS[contract.status] ?? ""} variant="secondary">
                {STATUS_LABELS[contract.status] ?? contract.status}
              </Badge>
            </div>
            <p className="text-sm text-muted-foreground">
              Version {contract.version} &middot; {format(new Date(contract.created_at), "MMM dd, yyyy")}
              {contract.ai_model && ` · Generated by ${contract.ai_model}`}
            </p>
          </div>
        </div>
        <Button variant="outline"><Download className="mr-2 h-4 w-4" />Download PDF</Button>
      </div>

      <Card>
        <CardHeader><CardTitle>Contract Content</CardTitle></CardHeader>
        <CardContent>
          <div className="whitespace-pre-wrap rounded-lg bg-muted p-6 font-mono text-sm leading-relaxed">
            {contract.content || "No content available."}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
